version: '2'
services:
  sonarqube:
    image: bitnami/sonarqube:latest
    ports:
      - '8443:8443'
    environment:
      - SONARQUBE_JDBC_URL=jdbc:sqlserver://host.docker.internal:1433;databaseName=sonarqube
      - SONARQUBE_JDBC_USERNAME=sa
      - SONARQUBE_JDBC_PASSWORD=udanjo2011@  
      - ALLOW_EMPTY_PASSWORD=yes
      # - SONARQUBE_DATABASE_HOST=host.docker.internal
      # - SONARQUBE_DATABASE_PORT_NUMBER=5434
      # - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
      # - SONARQUBE_DATABASE_USER=bn_sonarqube
      # - SONARQUBE_DATABASE_PASSWORD=bitnami1234
    volumes:
      - sonarqube_data:/bitnami
volumes:
  sonarqube_data:
    driver: local
