version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: 'rabbit'
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - docker-network
    volumes:
      - docker-volume:/etc/rabbitmq/rabbitmq.config

networks:
  docker-network:
    driver: bridge

volumes:
  docker-volume:
    driver: local