FROM jboss/keycloak:15.0.2

ENV KEYCLOAK_USER admin
ENV KEYCLOAK_PASSWORD admin

COPY custom-realm.json /opt/jboss/keycloak/

CMD ["-b", "0.0.0.0", "-Djboss.http.port=8080", "-Dkeycloak.import=/opt/jboss/keycloak/custom-realm.json"]

EXPOSE 8080