# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    #restart: always
    volumes:
      - /e/Container-Docker/MongoDB/data/db
    # volumes:
      # - type: bind
        # source: e/Container-Docker/MongoDB/
        # target: /data/db
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge